# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-8OkqaTDktlOn1ILIbXysXubzs3GU-6
"""

import pandas as pd

results=pd.read_csv('results.csv')

results['date']=pd.to_datetime(results['date'])

results=results[results['date']>="1990-1-1"]

results.sort_values('date')

df=results.dropna(subset=["home_score","away_score"])

df.shape
df.head()

def getResult(row):
  if row['home_score']>row['away_score']:
    return 0
  elif row['home_score']<row['away_score']:
    return 2
  else:
    return 1
df["result"]=df.apply(getResult,axis=1)

df.drop_duplicates()
df.head()

def determine_k_factor(tournament):
    tourn_lower = tournament.lower()
    if "friendly" in tourn_lower:
        return 20
    elif "world cup" in tourn_lower and "qualif" not in tourn_lower:
        return 60
    elif any(comp in tourn_lower for comp in ["euro", "copa am", "african cup of nations", "asian cup", "gold cup", "nations cup", "nations league"]):
        if "qualif" in tourn_lower:
            return 30
        return 50
    elif "qualif" in tourn_lower or "preliminary" in tourn_lower:
        return 40
    else:
        return 30

def calculate_elo_ratings(df):
    print("Calculating historical Elo ratings...")
    # Initialize team ratings dictionary
    team_ratings = {}
    default_rating = 1500.0
    home_field_advantage = 100.0

    # Lists to store pre-match Elo ratings for each row
    elo_home_list = []
    elo_away_list = []
    elo_diff_list = []
    elo_prob_home_list = []
    elo_prob_away_list = []

    # Iterate through matches chronologically
    for idx, row in df.iterrows():
        home = row["home_team"]
        away = row["away_team"]
        neutral = row["neutral"]
        tournament = row["tournament"]

        # Get current ratings
        r_home = team_ratings.get(home, default_rating)
        r_away = team_ratings.get(away, default_rating)

        # Store pre-match ratings
        elo_home_list.append(r_home)
        elo_away_list.append(r_away)

        # Adjust for home field advantage in probability calculation
        h_adj = 0.0 if neutral else home_field_advantage
        elo_diff = (r_home + h_adj) - r_away
        elo_diff_list.append(elo_diff)

        # Expected scores
        e_home = 1.0 / (1.0 + 10.0 ** (-elo_diff / 400.0))
        e_away = 1.0 - e_home

        elo_prob_home_list.append(e_home)
        elo_prob_away_list.append(e_away)

        # Actual scores
        if row["home_score"] > row["away_score"]:
            s_home, s_away = 1.0, 0.0
        elif row["away_score"] > row["home_score"]:
            s_home, s_away = 0.0, 1.0
        else:
            s_home, s_away = 0.5, 0.5

        # Determine K-factor
        k = determine_k_factor(tournament)

        # Update ratings
        r_home_new = r_home + k * (s_home - e_home)
        r_away_new = r_away + k * (s_away - e_away)

        # Save updated ratings back
        team_ratings[home] = r_home_new
        team_ratings[away] = r_away_new

    # Add columns to dataframe
    df["elo_home"] = elo_home_list
    df["elo_away"] = elo_away_list
    df["elo_diff"] = elo_diff_list
    df["elo_prob_home"] = elo_prob_home_list
    df["elo_prob_away"] = elo_prob_away_list

    print(f"Elo calculations complete. Total unique teams tracked: {len(team_ratings)}")
    return df, team_ratings

df_elo, final_ratings = calculate_elo_ratings(df)

df_elo.tail()

from collections import defaultdict

# -----------------------------
# Helper Function
# -----------------------------
def get_form_features(history):
    last5 = history[-5:]

    if len(last5) == 0:
        return (
            0, 0, 0,      # wins, draws, losses
            0, 0, 0       # goals scored avg, goals conceded avg, goal diff avg
        )

    wins = sum(x["result"] == "W" for x in last5)
    draws = sum(x["result"] == "D" for x in last5)
    losses = sum(x["result"] == "L" for x in last5)

    goals_scored = sum(x["goals_for"] for x in last5) / len(last5)
    goals_conceded = sum(x["goals_against"] for x in last5) / len(last5)

    goal_diff = sum(
        x["goals_for"] - x["goals_against"]
        for x in last5
    ) / len(last5)

    return (
        wins,
        draws,
        losses,
        goals_scored,
        goals_conceded,
        goal_diff
    )


# -----------------------------
# Team History Storage
# -----------------------------
team_history = defaultdict(list)

# -----------------------------
# Feature Lists
# -----------------------------
home_wins_last5 = []
away_wins_last5 = []

home_draws_last5 = []
away_draws_last5 = []

home_losses_last5 = []
away_losses_last5 = []

home_goals_scored_avg5 = []
away_goals_scored_avg5 = []

home_goals_conceded_avg5 = []
away_goals_conceded_avg5 = []

home_goal_diff_avg5 = []
away_goal_diff_avg5 = []

# -----------------------------
# Main Loop
# df must already be sorted by date
# -----------------------------
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    # Get form BEFORE current match
    home_features = get_form_features(team_history[home])
    away_features = get_form_features(team_history[away])

    # Store Home Features
    home_wins_last5.append(home_features[0])
    home_draws_last5.append(home_features[1])
    home_losses_last5.append(home_features[2])
    home_goals_scored_avg5.append(home_features[3])
    home_goals_conceded_avg5.append(home_features[4])
    home_goal_diff_avg5.append(home_features[5])

    # Store Away Features
    away_wins_last5.append(away_features[0])
    away_draws_last5.append(away_features[1])
    away_losses_last5.append(away_features[2])
    away_goals_scored_avg5.append(away_features[3])
    away_goals_conceded_avg5.append(away_features[4])
    away_goal_diff_avg5.append(away_features[5])

    # Determine Match Result
    if row["home_score"] > row["away_score"]:
        home_result = "W"
        away_result = "L"

    elif row["home_score"] < row["away_score"]:
        home_result = "L"
        away_result = "W"

    else:
        home_result = "D"
        away_result = "D"

    # Update Home History
    team_history[home].append({
        "result": home_result,
        "goals_for": row["home_score"],
        "goals_against": row["away_score"]
    })

    # Update Away History
    team_history[away].append({
        "result": away_result,
        "goals_for": row["away_score"],
        "goals_against": row["home_score"]
    })

# -----------------------------
# Add Features to DataFrame
# -----------------------------
df["home_wins_last5"] = home_wins_last5
df["away_wins_last5"] = away_wins_last5

df["home_draws_last5"] = home_draws_last5
df["away_draws_last5"] = away_draws_last5

df["home_losses_last5"] = home_losses_last5
df["away_losses_last5"] = away_losses_last5

df["home_goals_scored_avg5"] = home_goals_scored_avg5
df["away_goals_scored_avg5"] = away_goals_scored_avg5

df["home_goals_conceded_avg5"] = home_goals_conceded_avg5
df["away_goals_conceded_avg5"] = away_goals_conceded_avg5

df["home_goal_diff_avg5"] = home_goal_diff_avg5
df["away_goal_diff_avg5"] = away_goal_diff_avg5

# -----------------------------
# Additional Difference Features
# -----------------------------
df["form_diff"] = (
    df["home_wins_last5"] -
    df["away_wins_last5"]
)

df["goal_diff_diff"] = (
    df["home_goal_diff_avg5"] -
    df["away_goal_diff_avg5"]
)

print("Form features generated successfully!")
print(df[[
    "home_team",
    "away_team",
    "home_wins_last5",
    "away_wins_last5",
    "home_goal_diff_avg5",
    "away_goal_diff_avg5"
]].tail())

def tournament_importance(tournament):
    t = tournament.lower()

    if "friendly" in t:
        return 1

    elif "qualif" in t:
        return 2

    elif any(x in t for x in [
        "euro",
        "copa",
        "african",
        "asian",
        "gold cup"
    ]):
        return 3

    elif "world cup" in t:
        return 4

    return 2

df["tournament_importance"] = df["tournament"].apply(tournament_importance)

split_ind=int(len(df)*0.8)
train=df.iloc[:split_ind]
test=df.iloc[split_ind:]

features = [

"elo_home",
"elo_away",
"elo_diff",

"home_wins_last5",
"away_wins_last5",

"home_goals_scored_avg5",
"away_goals_scored_avg5",

"home_goals_conceded_avg5",
"away_goals_conceded_avg5",

"home_goal_diff_avg5",
"away_goal_diff_avg5",

"form_diff",
"goal_diff_diff",

"neutral",

"tournament_importance"
]
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(
    train[features],
    train["result"]
)

pred = model.predict(
    test[features]
)

from sklearn.metrics import accuracy_score

accuracy_score(test["result"],pred)

from sklearn.metrics import classification_report

print(
classification_report(
test["result"],
pred
)
)

from numpy import random
!pip install xgboost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    random_state=42
)

xgb.fit(
    train[features],
    train["result"]
)

import matplotlib.pyplot as plt

imp = pd.Series(
    xgb.feature_importances_,
    index=features
).sort_values()

imp.plot(kind="barh")
plt.show()