/**
 * Converts an ISO 3166-1 alpha-2 code to a flag emoji.
 * Uses Unicode Regional Indicator Symbols (U+1F1E6–U+1F1FF).
 */
function iso2ToFlag(iso2) {
  if (!iso2 || iso2.length !== 2) return "🏳️";
  return [...iso2.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join("");
}

/**
 * Map of team name → ISO 3166-1 alpha-2 code.
 */
const TEAM_ISO = {
  "Algeria": "DZ",
  "Mali": "ML",
  "Cameroon": "CM",
  "Greece": "GR",
  "Belgium": "BE",
  "Mexico": "MX",
  "Argentina": "AR",
  "Malawi": "MW",
  "Tanzania": "TZ",
  "Eswatini": "SZ",
  "Botswana": "BW",
  "Kuwait": "KW",
  "France": "FR",
  "German DR": "DE",
  "Liberia": "LR",
  "Senegal": "SN",
  "Nigeria": "NG",
  "Ivory Coast": "CI",
  "United Arab Emirates": "AE",
  "Egypt": "EG",
  "Thailand": "TH",
  "Kenya": "KE",
  "Colombia": "CO",
  "Uruguay": "UY",
  "Indonesia": "ID",
  "Iran": "IR",
  "Poland": "PL",
  "United States": "US",
  "Costa Rica": "CR",
  "Romania": "RO",
  "South Korea": "KR",
  "Norway": "NO",
  "Denmark": "DK",
  "Malta": "MT",
  "Uganda": "UG",
  "Mauritius": "MU",
  "Togo": "TG",
  "Finland": "FI",
  "Bermuda": "BM",
  "Sweden": "SE",
  "Iraq": "IQ",
  "Russia": "RU",
  "Gambia": "GM",
  "Guinea-Bissau": "GW",
  "Bahrain": "BH",
  "Morocco": "MA",
  "Netherlands": "NL",
  "Italy": "IT",
  "Spain": "ES",
  "Czechoslovakia": "CZ",
  "Oman": "OM",
  "Qatar": "QA",
  "Austria": "AT",
  "Germany": "DE",
  "Zambia": "ZM",
  "Mozambique": "MZ",
  "Angola": "AO",
  "Lesotho": "LS",
  "Zimbabwe": "ZW",
  "Jamaica": "JM",
  "Barbados": "BB",
  "Hungary": "HU",
  "Basque Country": "ES",
  "Sint Maarten": "SX",
  "Cayman Islands": "KY",
  "Saint Kitts and Nevis": "KN",
  "Antigua and Barbuda": "AG",
  "Saint Martin": "MF",
  "British Virgin Islands": "VG",
  "Northern Ireland": "GB",
  "England": "GB",
  "Brazil": "BR",
  "Israel": "IL",
  "Republic of Ireland": "IE",
  "Wales": "GB",
  "Luxembourg": "LU",
  "Iceland": "IS",
  "Yugoslavia": "RS",
  "Scotland": "GB",
  "Switzerland": "CH",
  "Guernsey": "GG",
  "Turkey": "TR",
  "Saint Lucia": "LC",
  "Grenada": "GD",
  "Curaçao": "CW",
  "Martinique": "MQ",
  "French Guiana": "GF",
  "Saint Vincent and the Grenadines": "VC",
  "Dominica": "DM",
  "Gabon": "GA",
  "Suriname": "SR",
  "Guyana": "GY",
  "Guadeloupe": "GP",
  "Bulgaria": "BG",
  "Jersey": "JE",
  "Andalusia": "ES",
  "Canada": "CA",
  "Mauritania": "MR",
  "Burkina Faso": "BF",
  "Georgia": "GE",
  "Lithuania": "LT",
  "Ghana": "GH",
  "Albania": "AL",
  "Liechtenstein": "LI",
  "Jordan": "JO",
  "Tunisia": "TN",
  "Namibia": "NA",
  "China": "CN",
  "North Korea": "KP",
  "Japan": "JP",
  "Trinidad and Tobago": "TT",
  "DR Congo": "CD",
  "Faroe Islands": "FO",
  "Réunion": "RE",
  "New Zealand": "NZ",
  "Ethiopia": "ET",
  "Sudan": "SD",
  "Singapore": "SG",
  "Guinea": "GN",
  "Sierra Leone": "SL",
  "Madagascar": "MG",
  "Benin": "BJ",
  "Chad": "TD",
  "Niger": "NE",
  "Comoros": "KM",
  "Australia": "AU",
  "Seychelles": "SC",
  "Portugal": "PT",
  "Malaysia": "MY",
  "Yemen": "YE",
  "Pakistan": "PK",
  "Hong Kong": "HK",
  "Saudi Arabia": "SA",
  "Bangladesh": "BD",
  "Aruba": "AW",
  "Croatia": "HR",
  "Cyprus": "CY",
  "Fiji": "FJ",
  "Solomon Islands": "SB",
  "New Caledonia": "NC",
  "Vanuatu": "VU",
  "Papua New Guinea": "PG",
  "Chile": "CL",
  "San Marino": "SM",
  "Guatemala": "GT",
  "Zanzibar": "TZ",
  "Central African Republic": "CF",
  "Equatorial Guinea": "GQ",
  "India": "IN",
  "Paraguay": "PY",
  "Nicaragua": "NI",
  "El Salvador": "SV",
  "Haiti": "HT",
  "Puerto Rico": "PR",
  "Montserrat": "MS",
  "Dominican Republic": "DO",
  "Panama": "PA",
  "Honduras": "HN",
  "Anguilla": "AI",
  "Peru": "PE",
  "Ecuador": "EC",
  "Bolivia": "BO",
  "Slovenia": "SI",
  "Philippines": "PH",
  "Brunei": "BN",
  "Åland Islands": "AX",
  "Greenland": "GL",
  "Moldova": "MD",
  "Venezuela": "VE",
  "Guam": "GU",
  "Tahiti": "PF",
  "Wallis Islands and Futuna": "WF",
  "Estonia": "EE",
  "Latvia": "LV",
  "Cape Verde": "CV",
  "Vietnam": "VN",
  "Myanmar": "MM",
  "Libya": "LY",
  "Sri Lanka": "LK",
  "Nepal": "NP",
  "Maldives": "MV",
  "Ukraine": "UA",
  "Cuba": "CU",
  "Syria": "SY",
  "Kazakhstan": "KZ",
  "Turkmenistan": "TM",
  "Taiwan": "TW",
  "Macau": "MO",
  "Tajikistan": "TJ",
  "Uzbekistan": "UZ",
  "Burundi": "BI",
  "Eritrea": "ER",
  "Slovakia": "SK",
  "South Africa": "ZA",
  "Kyrgyzstan": "KG",
  "Palestine": "PS",
  "Azerbaijan": "AZ",
  "Armenia": "AM",
  "Belarus": "BY",
  "Lebanon": "LB",
  "Mongolia": "MN",
  "Laos": "LA",
  "Isle of Man": "IM",
  "Gibraltar": "GI",
  "North Macedonia": "MK",
  "Tonga": "TO",
  "Czech Republic": "CZ",
  "Samoa": "WS",
  "American Samoa": "AS",
  "Somalia": "SO",
  "Djibouti": "DJ",
  "Serbia": "RS",
  "Cook Islands": "CK",
  "Rwanda": "RW",
  "Belize": "BZ",
  "Bosnia and Herzegovina": "BA",
  "Cambodia": "KH",
  "Andorra": "AD",
  "Catalonia": "ES",
  "United States Virgin Islands": "VI",
  "Corsica": "FR",
  "Brittany": "FR",
  "Northern Mariana Islands": "MP",
  "Palau": "PW",
  "São Tomé and Príncipe": "ST",
  "Bahamas": "BS",
  "Turks and Caicos Islands": "TC",
  "Micronesia": "FM",
  "Bhutan": "BT",
  "Monaco": "MC",
  "Western Sahara": "EH",
  "Falkland Islands": "FK",
  "Mayotte": "YT",
  "Vatican City": "VA",
  "Afghanistan": "AF",
  "Timor-Leste": "TL",
  "Tuvalu": "TV",
  "Kiribati": "KI",
  "Occitania": "FR",
  "Galicia": "ES",
  "Kosovo": "XK",
  "Montenegro": "ME",
  "Provence": "FR",
  "Saint Barthélemy": "BL",
  "Saint Pierre and Miquelon": "PM",
  "Bonaire": "BQ",
  "South Sudan": "SS",
  "Marshall Islands": "MH",
};

/** Returns the flag emoji for a team name (falls back to 🏳️). */
export function flagEmoji(teamName) {
  const iso = TEAM_ISO[teamName];
  if (!iso) return "🏳️";
  return iso2ToFlag(iso);
}

/** Returns the ISO 3166-1 alpha-2 code for a team name. */
export function isoCode(teamName) {
  return TEAM_ISO[teamName] || null;
}
